import { Task } from "../../dist/types/public-types";

export function initTasks() {
  // const currentDate = new Date();
  const tasks: Task[] = [
    {
      start: new Date(2023, 0, 1),
      end: new Date(2024, 0, 1),
      name: '金利情報',
      seconds: 60,
      remaining: 60,
      id: 'Task 0',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 0, 31),
      end: new Date(2030, 4, 30),
      name: 'DEF',
      seconds: 60,
      remaining: 60,
      id: 'Task 1',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 0, 11),
      end: new Date(2023, 0, 30),
      name: 'GHI',
      seconds: 60,
      remaining: 60,
      id: 'Task 2',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 3, 11),
      end: new Date(2023, 4, 30),
      name: 'JKL',
      seconds: 60,
      remaining: 60,
      id: 'Task 3',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 4, 6),
      end: new Date(2023, 4, 30),
      name: 'MNO',
      seconds: 60,
      remaining: 60,
      id: 'Task 4',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 8, 1),
      end: new Date(2023, 8, 20),
      name: 'PQR',
      seconds: 60,
      remaining: 60,
      id: 'Task 5',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 9, 20),
      end: new Date(2023, 9, 28),
      name: 'STU',
      seconds: 60,
      remaining: 60,
      id: 'Task 6',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 9, 2),
      end: new Date(2023, 9, 25),
      name: 'VWX',
      seconds: 60,
      remaining: 60,
      id: 'Task 7',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 12, 1),
      end: new Date(2023, 12, 25),
      name: 'YZA',
      seconds: 60,
      remaining: 60,
      id: 'Task 8',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 11, 5),
      end: new Date(2023, 11, 20),
      name: 'BCD',
      seconds: 60,
      remaining: 60,
      id: 'Task 9',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 10, 1),
      end: new Date(2023, 10, 16),
      name: 'EFG',
      seconds: 60,
      remaining: 60,
      id: 'Task 10',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 1, 1),
      end: new Date(2023, 1, 12),
      name: 'HIJ',
      seconds: 60,
      remaining: 60,
      id: 'Task 11',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },{
      start: new Date(2023, 0, 1),
      end: new Date(2023, 0, 31),
      name: 'KLN',
      seconds: 60,
      remaining: 60,
      id: 'Task 12',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 2, 10),
      end: new Date(2023, 2, 18),
      name: 'MOP',
      seconds: 60,
      remaining: 60,
      id: 'Task 13',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 5, 1),
      end: new Date(2023, 5, 18),
      name: 'QRS',
      seconds: 60,
      remaining: 60,
      id: 'Task 14',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 4, 1),
      end: new Date(2023, 4, 5),
      name: 'TUV',
      seconds: 60,
      remaining: 60,
      id: 'Task 15',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 4, 6),
      end: new Date(2023, 4, 30),
      name: 'WXY',
      seconds: 60,
      remaining: 60,
      id: 'Task 16',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 8, 1),
      end: new Date(2023, 8, 20),
      name: 'ZAB',
      seconds: 60,
      remaining: 60,
      id: 'Task 17',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 9, 20),
      end: new Date(2023, 9, 28),
      name: 'CDE',
      seconds: 60,
      remaining: 60,
      id: 'Task 18',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 9, 2),
      end: new Date(2023, 9, 25),
      name: 'FGH',
      seconds: 60,
      remaining: 60,
      id: 'Task 19',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 12, 1),
      end: new Date(2023, 12, 25),
      name: 'IJK',
      seconds: 60,
      remaining: 60,
      id: 'Task 20',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 11, 5),
      end: new Date(2023, 11, 20),
      name: 'LMN',
      seconds: 60,
      remaining: 60,
      id: 'Task 21',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 10, 1),
      end: new Date(2024, 10, 1),
      name: 'OPQ',
      seconds: 60,
      remaining: 60,
      id: 'Task 22',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      start: new Date(2023, 1, 1),
      end: new Date(2023, 1, 12),
      name: 'RST',
      seconds: 60,
      remaining: 60,
      id: 'Task 23',
      type:'task',
      progress: 100,
      isDisabled: true,
      styles: { progressColor: '#ffbb54', progressSelectedColor: '#ff9e0d' },
    },
    {
      id: 'broadcastTime',
      name: '放送時間',
      start: new Date(2023, 1, 1),
      end: new Date(2023, 1, 2),
      progress: 0,
      isDisabled: true,
      type: "task",
      seconds: 0,
      remaining: 0
    },
    {
      id: 'remainingTime',
      name: '残り時間',
      start: new Date(2023, 1, 1),
      end: new Date(2023, 1, 2),
      progress: 0,
      isDisabled: true,
      type: "task",
      seconds: 0,
      remaining: 0
    }
  ];
  return tasks;
}

export function getStartEndDateForProject(tasks: Task[], projectId: string) {
  const projectTasks = tasks.filter(t => t.project === projectId);
  let start = projectTasks[0].start;
  let end = projectTasks[0].end;

  for (let i = 0; i < projectTasks.length; i++) {
    const task = projectTasks[i];
    if (start.getTime() > task.start.getTime()) {
      start = task.start;
    }
    if (end.getTime() < task.end.getTime()) {
      end = task.end;
    }
  }
  return [start, end];
}
